name = "order-management-api"
main = "src/server.ts"
compatibility_date = "2024-01-01"

[[ d1_databases ]]
binding = "DB"
database_name = "order_management_db"
database_id = "eed608df-bfde-4e4f-91c6-4401dc958284"

[[ r2_buckets ]]
binding = "LOGS_BUCKET"
bucket_name = "application-logs"